{ pkgs, ... }:

{
  users = {
    # set user's default shell system-wide
    defaultUserShell = pkgs.bash;

    # set user groups
    groups = {
      evims = { };
    };

    # Define a user account. Don't forget to set a password with ‘passwd’.
    users.evims = {
      name = "evims";
      home = "/home/evims";
      isNormalUser = true;
      description = "emacs vim";
      shell = pkgs.fish;
      # the hashed password with salt is generated by run `mkpasswd`.  usage: mkpasswd --method=yescrypt
      hashedPassword = "$y$j9T$LHL7xn4usAEZpuKy7Mtck1$nCIduiUCyOUcFwbmkdIkA1WtMQFx1W9zaEFHJ6KgGC6";
      extraGroups = [ 
        "evims" 
        "users"
        "networkmanager" 
        "wheel"
        "docker"
        "dialout"
        "video"
        "audio"
      ];
    };
  };
}
